import { Qualifier, FactQualifier } from './qualifier';

export interface Fact<T> {
  date?: Date;
  place?: string;
  type: T;
  value?: string;
  qualifiers?: Qualifier<FactQualifier>[];
}

export enum PersonFactType {
  Custom = 'custom',
  Adoption = 'adoption',
  AdultChristening = 'adultChristening',
  Amnesty = 'amnesty',
  Apprenticeship = 'apprenticeship',
  Arrest = 'arrest',
  Award = 'award',
  Baptism = 'baptism',
  BarMitzvah = 'barMitzvah',
  BatMitzvah = 'batMitzvah',
  Birth = 'birth',
  BirthNotice = 'birthNotice',
  Blessing = 'blessing',
  Burial = 'burial',
  Caste = 'caste',
  Census = 'census',
  Christening = 'christening',
  Circumcision = 'circumcision',
  Clan = 'clan',
  Confirmation = 'confirmation',
  Court = 'court',
  Cremation = 'cremation',
  Death = 'death',
  Education = 'education',
  EducationEnrollment = 'educationEnrollment',
  Emigration = 'emigration',
  Enslavement = 'enslavement',
  Ethnicity = 'ethnicity',
  Excommunication = 'excommunication',
  FirstCommunion = 'firstCommunion',
  Funeral = 'funeral',
  GenderChange = 'genderChange',
  Graduation = 'graduation',
  Heimat = 'heimat',
  Immigration = 'immigration',
  Imprisonment = 'imprisonment',
  Inquest = 'inquest',
  LandTransaction = 'landTransaction',
  Language = 'language',
  Living = 'living',
  MaritalStatus = 'maritalStatus',
  Medical = 'medical',
  MilitaryAward = 'militaryAward',
  MilitaryDischarge = 'militaryDischarge',
  MilitaryDraftRegistration = 'militaryDraftRegistration',
  MilitaryInduction = 'militaryInduction',
  MilitaryService = 'militaryService',
  Mission = 'mission',
  MoveFrom = 'moveFrom',
  MoveTo = 'moveTo',
  MultipleBirth = 'multipleBirth',
  NationalId = 'nationalId',
  Nationality = 'nationality',
  Naturalization = 'naturalization',
  NumberOfChildren = 'numberOfChildren',
  NumberOfMarriages = 'numberOfMarriages',
  Obituary = 'obituary',
  Occupation = 'occupation',
  Ordination = 'ordination',
  Pardon = 'pardon',
  PhysicalDescription = 'physicalDescription',
  Probate = 'probate',
  Property = 'property',
  Race = 'race',
  Religion = 'religion',
  Residence = 'residence',
  Retirement = 'retirement',
  Stillbirth = 'stillbirth',
  TaxAssessment = 'taxAssessment',
  Tribe = 'tribe',
  Will = 'will',
  Visit = 'visit',
  Yahrzeit = 'yahrzeit',
}

export enum CoupleRelationshipFactType {
  Custom = 'custom',
  Annulment = 'annulment',
  CommonLawMarriage = 'commonLawMarriage',
  CivilUnion = 'civilUnion',
  Divorce = 'divorce',
  DivorceFiling = 'divorceFiling',
  DomesticPartnership = 'domesticPartnership',
  Engagement = 'engagement',
  Marriage = 'marriage',
  MarriageBanns = 'marriageBanns',
  MarriageContract = 'marriageContract',
  MarriageLicense = 'marriageLicense',
  MarriageNotice = 'marriageNotice',
  NumberOfChildren = 'numberOfChildren',
  Separation = 'separation',
}

export enum ParentChildRelationshipFactType {
  AdoptiveParent = 'adoptiveParent',
  BiologicalParent = 'biologicalParent',
  FosterParent = 'fosterParent',
  GuardianParent = 'guardianParent',
  StepParent = 'stepParent',
  SociologicalParent = 'sociologicalParent',
  SurrogateParent = 'surrogateParent',
}
